# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI / CD

to:
Push:
branches: [master]
donsa_cela:
branches: [master]

jobs:
to build:

    advances: personality-latest

    site:
      matrix:
        Node type: [12.x]

    steps:
    - name: Storage location
      uses: actions / checkout @ v2

    - name: Set Node.js $ {{matrix.node-version}}
      uses: actions / setup-node @ v1
      no:
        version-node: $ {{matrix.node-version}}

    - name: Enter dependency
      run: npm to install

    - name: Launch tests
      run: npm test

    - name: Build
      run: npm run build
